//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cudanawidelcu.ds360.pl/", ConfigurationName="RecipeReference.RecipeService")]
    public interface RecipeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/rateRecipeRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/rateRecipeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.rateRecipeResponse> rateRecipeAsync(RecipeReference.rateRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/getRecipesRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/getRecipesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.getRecipesResponse> getRecipesAsync(RecipeReference.getRecipesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/rateRecipeByNameRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/rateRecipeByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.rateRecipeByNameResponse> rateRecipeByNameAsync(RecipeReference.rateRecipeByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/addRecipeRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/addRecipeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.addRecipeResponse> addRecipeAsync(RecipeReference.addRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/getRecipeByNameRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/getRecipeByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.getRecipeByNameResponse> getRecipeByNameAsync(RecipeReference.getRecipeByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/deleteRecipeRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/deleteRecipeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.deleteRecipeResponse> deleteRecipeAsync(RecipeReference.deleteRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/modifyRecipeRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/modifyRecipeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.modifyRecipeResponse> modifyRecipeAsync(RecipeReference.modifyRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/getRecipeRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/getRecipeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.getRecipeResponse> getRecipeAsync(RecipeReference.getRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/getRecipesToStringRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/getRecipesToStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.getRecipesToStringResponse> getRecipesToStringAsync(RecipeReference.getRecipesToStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/getRecipesByCategoryRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/getRecipesByCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.getRecipesByCategoryResponse> getRecipesByCategoryAsync(RecipeReference.getRecipesByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cudanawidelcu.ds360.pl/RecipeService/deleteRecipeByNameRequest", ReplyAction="http://cudanawidelcu.ds360.pl/RecipeService/deleteRecipeByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipeReference.deleteRecipeByNameResponse> deleteRecipeByNameAsync(RecipeReference.deleteRecipeByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rateRecipe", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class rateRecipeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int vote;
        
        public rateRecipeRequest()
        {
        }
        
        public rateRecipeRequest(int id, int vote)
        {
            this.id = id;
            this.vote = vote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rateRecipeResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class rateRecipeResponse
    {
        
        public rateRecipeResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cudanawidelcu.ds360.pl/")]
    public partial class Recipe
    {
        
        private Category categoryField;
        
        private bool categoryFieldSpecified;
        
        private int countVotesField;
        
        private string descriptionField;
        
        private int idField;
        
        private byte[] imageField;
        
        private string nameField;
        
        private int nextProductIdField;
        
        private Product[] productsField;
        
        private double ratingField;
        
        private bool ratingFieldSpecified;
        
        private System.Nullable<int>[] votesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Category category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified
        {
            get
            {
                return this.categoryFieldSpecified;
            }
            set
            {
                this.categoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int countVotes
        {
            get
            {
                return this.countVotesField;
            }
            set
            {
                this.countVotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nextProductId
        {
            get
            {
                return this.nextProductIdField;
            }
            set
            {
                this.nextProductIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("products", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public Product[] products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ratingSpecified
        {
            get
            {
                return this.ratingFieldSpecified;
            }
            set
            {
                this.ratingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("votes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int>[] votes
        {
            get
            {
                return this.votesField;
            }
            set
            {
                this.votesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cudanawidelcu.ds360.pl/")]
    public enum Category
    {
        
        /// <remarks/>
        BREAKFAST,
        
        /// <remarks/>
        LUNCH,
        
        /// <remarks/>
        DINNER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cudanawidelcu.ds360.pl/")]
    public partial class Product
    {
        
        private int idField;
        
        private string measureField;
        
        private string nameField;
        
        private double qtyField;
        
        private bool qtyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string measure
        {
            get
            {
                return this.measureField;
            }
            set
            {
                this.measureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qtySpecified
        {
            get
            {
                return this.qtyFieldSpecified;
            }
            set
            {
                this.qtyFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipes", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipesRequest
    {
        
        public getRecipesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipesResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Recipe[] @return;
        
        public getRecipesResponse()
        {
        }
        
        public getRecipesResponse(RecipeReference.Recipe[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rateRecipeByName", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class rateRecipeByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int vote;
        
        public rateRecipeByNameRequest()
        {
        }
        
        public rateRecipeByNameRequest(string name, int vote)
        {
            this.name = name;
            this.vote = vote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rateRecipeByNameResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class rateRecipeByNameResponse
    {
        
        public rateRecipeByNameResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addRecipe", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class addRecipeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Recipe recipe;
        
        public addRecipeRequest()
        {
        }
        
        public addRecipeRequest(RecipeReference.Recipe recipe)
        {
            this.recipe = recipe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addRecipeResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class addRecipeResponse
    {
        
        public addRecipeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipeByName", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipeByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public getRecipeByNameRequest()
        {
        }
        
        public getRecipeByNameRequest(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipeByNameResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipeByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Recipe @return;
        
        public getRecipeByNameResponse()
        {
        }
        
        public getRecipeByNameResponse(RecipeReference.Recipe @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRecipe", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class deleteRecipeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public deleteRecipeRequest()
        {
        }
        
        public deleteRecipeRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRecipeResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class deleteRecipeResponse
    {
        
        public deleteRecipeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyRecipe", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class modifyRecipeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Recipe recipe;
        
        public modifyRecipeRequest()
        {
        }
        
        public modifyRecipeRequest(RecipeReference.Recipe recipe)
        {
            this.recipe = recipe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyRecipeResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class modifyRecipeResponse
    {
        
        public modifyRecipeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipe", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getRecipeRequest()
        {
        }
        
        public getRecipeRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipeResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Recipe @return;
        
        public getRecipeResponse()
        {
        }
        
        public getRecipeResponse(RecipeReference.Recipe @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipesToString", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipesToStringRequest
    {
        
        public getRecipesToStringRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipesToStringResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipesToStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getRecipesToStringResponse()
        {
        }
        
        public getRecipesToStringResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipesByCategory", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipesByCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Category category;
        
        public getRecipesByCategoryRequest()
        {
        }
        
        public getRecipesByCategoryRequest(RecipeReference.Category category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecipesByCategoryResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class getRecipesByCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecipeReference.Recipe[] @return;
        
        public getRecipesByCategoryResponse()
        {
        }
        
        public getRecipesByCategoryResponse(RecipeReference.Recipe[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRecipeByName", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class deleteRecipeByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cudanawidelcu.ds360.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public deleteRecipeByNameRequest()
        {
        }
        
        public deleteRecipeByNameRequest(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRecipeByNameResponse", WrapperNamespace="http://cudanawidelcu.ds360.pl/", IsWrapped=true)]
    public partial class deleteRecipeByNameResponse
    {
        
        public deleteRecipeByNameResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface RecipeServiceChannel : RecipeReference.RecipeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class RecipeServiceClient : System.ServiceModel.ClientBase<RecipeReference.RecipeService>, RecipeReference.RecipeService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecipeServiceClient() : 
                base(RecipeServiceClient.GetDefaultBinding(), RecipeServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RecipeServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipeServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RecipeServiceClient.GetBindingForEndpoint(endpointConfiguration), RecipeServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipeServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecipeServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipeServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecipeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.rateRecipeResponse> RecipeReference.RecipeService.rateRecipeAsync(RecipeReference.rateRecipeRequest request)
        {
            return base.Channel.rateRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.rateRecipeResponse> rateRecipeAsync(int id, int vote)
        {
            RecipeReference.rateRecipeRequest inValue = new RecipeReference.rateRecipeRequest();
            inValue.id = id;
            inValue.vote = vote;
            return ((RecipeReference.RecipeService)(this)).rateRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.getRecipesResponse> RecipeReference.RecipeService.getRecipesAsync(RecipeReference.getRecipesRequest request)
        {
            return base.Channel.getRecipesAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.getRecipesResponse> getRecipesAsync()
        {
            RecipeReference.getRecipesRequest inValue = new RecipeReference.getRecipesRequest();
            return ((RecipeReference.RecipeService)(this)).getRecipesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.rateRecipeByNameResponse> RecipeReference.RecipeService.rateRecipeByNameAsync(RecipeReference.rateRecipeByNameRequest request)
        {
            return base.Channel.rateRecipeByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.rateRecipeByNameResponse> rateRecipeByNameAsync(string name, int vote)
        {
            RecipeReference.rateRecipeByNameRequest inValue = new RecipeReference.rateRecipeByNameRequest();
            inValue.name = name;
            inValue.vote = vote;
            return ((RecipeReference.RecipeService)(this)).rateRecipeByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.addRecipeResponse> RecipeReference.RecipeService.addRecipeAsync(RecipeReference.addRecipeRequest request)
        {
            return base.Channel.addRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.addRecipeResponse> addRecipeAsync(RecipeReference.Recipe recipe)
        {
            RecipeReference.addRecipeRequest inValue = new RecipeReference.addRecipeRequest();
            inValue.recipe = recipe;
            return ((RecipeReference.RecipeService)(this)).addRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.getRecipeByNameResponse> RecipeReference.RecipeService.getRecipeByNameAsync(RecipeReference.getRecipeByNameRequest request)
        {
            return base.Channel.getRecipeByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.getRecipeByNameResponse> getRecipeByNameAsync(string name)
        {
            RecipeReference.getRecipeByNameRequest inValue = new RecipeReference.getRecipeByNameRequest();
            inValue.name = name;
            return ((RecipeReference.RecipeService)(this)).getRecipeByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.deleteRecipeResponse> RecipeReference.RecipeService.deleteRecipeAsync(RecipeReference.deleteRecipeRequest request)
        {
            return base.Channel.deleteRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.deleteRecipeResponse> deleteRecipeAsync(int id)
        {
            RecipeReference.deleteRecipeRequest inValue = new RecipeReference.deleteRecipeRequest();
            inValue.id = id;
            return ((RecipeReference.RecipeService)(this)).deleteRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.modifyRecipeResponse> RecipeReference.RecipeService.modifyRecipeAsync(RecipeReference.modifyRecipeRequest request)
        {
            return base.Channel.modifyRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.modifyRecipeResponse> modifyRecipeAsync(RecipeReference.Recipe recipe)
        {
            RecipeReference.modifyRecipeRequest inValue = new RecipeReference.modifyRecipeRequest();
            inValue.recipe = recipe;
            return ((RecipeReference.RecipeService)(this)).modifyRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.getRecipeResponse> RecipeReference.RecipeService.getRecipeAsync(RecipeReference.getRecipeRequest request)
        {
            return base.Channel.getRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.getRecipeResponse> getRecipeAsync(int id)
        {
            RecipeReference.getRecipeRequest inValue = new RecipeReference.getRecipeRequest();
            inValue.id = id;
            return ((RecipeReference.RecipeService)(this)).getRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.getRecipesToStringResponse> RecipeReference.RecipeService.getRecipesToStringAsync(RecipeReference.getRecipesToStringRequest request)
        {
            return base.Channel.getRecipesToStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.getRecipesToStringResponse> getRecipesToStringAsync()
        {
            RecipeReference.getRecipesToStringRequest inValue = new RecipeReference.getRecipesToStringRequest();
            return ((RecipeReference.RecipeService)(this)).getRecipesToStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.getRecipesByCategoryResponse> RecipeReference.RecipeService.getRecipesByCategoryAsync(RecipeReference.getRecipesByCategoryRequest request)
        {
            return base.Channel.getRecipesByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.getRecipesByCategoryResponse> getRecipesByCategoryAsync(RecipeReference.Category category)
        {
            RecipeReference.getRecipesByCategoryRequest inValue = new RecipeReference.getRecipesByCategoryRequest();
            inValue.category = category;
            return ((RecipeReference.RecipeService)(this)).getRecipesByCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeReference.deleteRecipeByNameResponse> RecipeReference.RecipeService.deleteRecipeByNameAsync(RecipeReference.deleteRecipeByNameRequest request)
        {
            return base.Channel.deleteRecipeByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeReference.deleteRecipeByNameResponse> deleteRecipeByNameAsync(string name)
        {
            RecipeReference.deleteRecipeByNameRequest inValue = new RecipeReference.deleteRecipeByNameRequest();
            inValue.name = name;
            return ((RecipeReference.RecipeService)(this)).deleteRecipeByNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecipeServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecipeServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:8181/cuda-na-widelcu-backend/RecipeService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecipeServiceClient.GetBindingForEndpoint(EndpointConfiguration.RecipeServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecipeServiceClient.GetEndpointAddress(EndpointConfiguration.RecipeServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            RecipeServiceImplPort,
        }
    }
}
